In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from gridding_python_improved.gridding import gcf_kaiser, gcf_kaiser_improved

In [3]:
gcf_kaiser(-1, 5, 0.1)

-0.4
0.84


0.9996005390997699

In [4]:
k = np.array([-1]).repeat(2)
Dk = np.array([5]).repeat(2)
beta = np.array(0.1).repeat(2)

In [5]:
gcf_kaiser_improved(k, Dk, beta)

array([0.99960054, 0.99960054])

In [112]:
from gridding_python_improved.gridding import grid_1d_from_2d, grid_1d_from_2di

In [240]:
x = np.random.randn(1)
vis = np.random.randn(1) + np.random.randn(1) * 1j
dx = 2/3
W = 6
beta = 12.24
y = np.random.randn(1)
x2 = np.zeros(6, dtype=complex)
vis2 = np.zeros(6, dtype=complex)
y2 = np.zeros(6, dtype=complex)
grid_1d_from_2d(x, vis, dx, W, beta, y, x2, vis2, y2)

In [241]:
x2

array([-2.        +0.j, -1.33333333+0.j, -0.66666667+0.j,  0.        +0.j,
        0.66666667+0.j,  1.33333333+0.j])

In [242]:
y2

array([-1.30259018+0.j, -1.30259018+0.j, -1.30259018+0.j, -1.30259018+0.j,
       -1.30259018+0.j, -1.30259018+0.j])

In [243]:
vis2

array([0.00793113-0.00625864j, 0.16792404-0.13251271j,
       0.51826413-0.40897411j, 0.40858274-0.32242201j,
       0.0748479 -0.0590642j , 0.00099494-0.00078513j])

In [244]:
x = x.repeat(32)
vis = vis.repeat(32)
y = y.repeat(32)
dx = 2/3
W = 6
beta = 12.24
# y = np.random.randn(5)
x2 = np.zeros(6, dtype=complex)
vis2 = np.zeros(6, dtype=complex)
y2 = np.zeros(6, dtype=complex)
x2, y2, vis2 = grid_1d_from_2di(x, vis, dx, W, beta, y, x2, vis2, y2)

(32,)
(32,)


In [245]:
x2.shape

(32, 6)

In [248]:
x2[0] == x2[-1]

array([ True,  True,  True,  True,  True,  True])

In [249]:
y2[0] == y2[-1]

array([ True,  True,  True,  True,  True,  True])

In [250]:
vis2[0] == vis2[-1]

array([ True,  True,  True,  True,  True,  True])

In [253]:
x2[0]

array([-2.        +0.j, -1.33333333+0.j, -0.66666667+0.j,  0.        +0.j,
        0.66666667+0.j,  1.33333333+0.j])

In [254]:
x2[0] == x2[-1], x2[0]

(array([ True,  True,  True,  True,  True,  True]),
 array([-2.        +0.j, -1.33333333+0.j, -0.66666667+0.j,  0.        +0.j,
         0.66666667+0.j,  1.33333333+0.j]))

In [255]:
y2.shape

(32, 6)

In [256]:
y2[0] == y2[-1], y2[0]

(array([ True,  True,  True,  True,  True,  True]),
 array([-1.30259018, -1.30259018, -1.30259018, -1.30259018, -1.30259018,
        -1.30259018]))

In [336]:
from gridding_python_improved.gridding import grid_2di, grid_2d

In [308]:
u = np.random.randn(8)
v = np.random.randn(8)
vis = np.random.randn(8) * np.random.randn(8) * 1j
du = 2/3
Nu = 3450
umin=-1150
dv = 2/3
Nv = 3450
umin=-1150
alpha = 1.5
W = 6
hflag_u = True
hflag_v = True


In [309]:
u.sum()

0.4674200641208046

In [310]:
grid_2d(u, v, vis, du, Nu, umin, dv, Nv, vmin, alpha, W, hflag_u, hflag_v)

10.623236362617092 0.6670597363998705j 1.9999999999999998
-7.153652793103089 0.002289604713318762j 10.0
-1.424968855264478 2.218611876074446j 1.9999999999999998
2.5606782204713756 -0.010274610216251041j -2.0000000000000004
4.468718785799142 -3.247140385330955j 1.9999999999999998
-8.655918631662662 -2.978117486745186j 1.9999999999999998
-12.984581719625405 1.349820225121312j -9.999999999999998
-4.9748438017730345 0.4209777120841703j -2.0000000000000004
-4.9748438017730345 0.4209777120841703j -2.0000000000000004


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [311]:
grid_2di(u, v, vis, du, Nu, umin, dv, Nv, vmin, alpha, W, hflag_u, hflag_v)

-1.5767733278992746j -17.541332432541058 (3.9999999999999982+0j)


RuntimeError: No active exception to reraise

In [443]:
def grid_1d_from_2d(x, vis, dx, W, beta, y, x2, vis2, y2):
    """
    Grid the data in w, Qvix, Uvis in 1D (x) and duplicate orthogonal axes
    """
    N = len(x)

    Dx = W*dx
    
    for indx in range(N):

        visval = vis[indx]

        xval = x[indx]
        yval = y[indx]
        
        xref = np.ceil((xval - 0.5*W*dx)/dx)*dx

        for xndx in range(W):
            
            xg = xref + xndx*dx
            
            kndx = indx*W + xndx
            
            gcf_val = gcf_kaiser(xg-xval, Dx, beta)
            
            
            vis2[kndx] = visval*gcf_val

            x2[kndx] = xg
            y2[kndx] = yval


In [604]:
def grid_1d_from_2di(x, vis, dx, W, beta, y, x2, vis2, y2):
#     Dx = W*dx
#     visval = vis

#     xval = x
#     xref = np.ceil((xval - 0.5*W*dx)/dx)*dx
    
#     xg = xref[:, None] + np.arange(W) * dx
    
#     gcf_val = gcf_kaiser_improved(xg - xval[:, None], Dx, beta)
#     vis2 = visval[:, None] * gcf_val
#     x2 = xg
#     y2 = np.tile(y[:, None], (1, W))
    
#     return x2, vis2, y2

    N = len(x)
    Dx = W * dx
    
    for indx in range(N):
        visval = vis[indx]
        
        xval = x[indx]
        yval = y[indx]
                
        xref = np.ceil((xval - 0.5*W*dx)/dx)*dx
                
        xndx = np.arange(W)
        
                
        xg = xref + xndx * dx
        
#         print(xg)
        
        kndx = indx * W + xndx
                        
        gcf_val = gcf_kaiser_improved(xg - xval, Dx, beta)
#         print(visval)
#         print(gcf_val)
#         print(vis2[kndx])
        vis2[kndx] = visval * gcf_val
#         print(visval * gcf_val)
        
#         print('\n')

    
#         print(vis2[kndx])
#         print(vis2[kndx])
        x2[kndx] = xg
        y2[kndx] = yval
        
    indx = np.arange(N)
    visval = vis[indx]
    xval = x[indx]
    yval = y[indx]

    xref = np.ceil((xval - 0.5*W*dx)/dx)*dx
    
    xndx = np.tile(np.arange(W)[None], (N, 1))
        
    xg = xref + xndx * dx
            
    kndx = np.arange(N * W).reshape(N, W)
    gcf_val = gcf_kaiser_improved(xg - xval, Dx, beta)
    
#     print(visval)
#     print(gcf_val[0])
#     print(np.outer(visval, gcf_val[0]))
    vis2[kndx] = np.outer(visval, gcf_val[0])
#     print(gcf_val)
#     print(visval)
#     print('\n')

#     print(gcf_val)
#     print('\n')
    
#     print(visval[None] * gcf_val)
#     print(visval * gcf_val)
#     vis2[kndx] = visval * gcf_val
#     print(vis2[kndx])
    x2[kndx] = xg
    y2[kndx] = yval

    return x2, vis2, y2

        

In [608]:
nvis = 4
u = np.random.randn(nvis)
v = np.random.randn(nvis)
vis = np.random.randn(nvis) * np.random.randn(nvis) * 1j
du = 2/3
Nu = 3450
umin=-1150
dv = 2/3
Nv = 3450
umin=-1150
alpha = 1.5
W = 6
hflag_u = True
hflag_v = True

tu1 = np.zeros(W)
tvis1 = np.zeros(W, dtype=complex)
tv1 = np.zeros(W)


tu1i = np.zeros(W)
tvis1i = np.zeros(W, dtype=complex)
tv1i = np.zeros(W)

su = np.zeros(1)
sv = np.zeros(1)
svis = np.zeros(1, dtype=complex)

tu2 = np.zeros(W2)
tvis2 = np.zeros(W2, dtype=complex)
tv2 = np.zeros(W2)

tu2i = np.zeros(W2)
tvis2i = np.zeros(W2, dtype=complex)
tv2i = np.zeros(W2)

W2 = W**2
nvis = u.shape[0]

for i in range(nvis):
    su[0] = u[i]
    sv[0] = v[i]
    svis[0] = vis[i]
    grid_1d_from_2d(su, svis, du, W, beta, sv, tu1, tvis1, tv1)
    
    grid_1d_from_2d(tv1, tvis1, dv, W, beta, tu1, tv2, tvis2, tu2) # output arrays

    tu1i, tvis1i, tv1i = grid_1d_from_2di(su, svis, du, W, beta, sv, tu1i, tvis1i, tv1i)
    
    tv2i, tvis2i, tu2i = grid_1d_from_2di(tv1i, tvis1i, dv, W, beta, tu1i, tv2i, tvis2i, tu2i) # output arrays


    print(tvis1.sum())
    print(tu1.sum())
    print(tv1.sum())
    
    print(tvis2.sum())
    print(tu2.sum())
    print(tv2.sum())
    
    print('\n')
       
    print(tvis1i.sum())
    print(tu1i.sum())
    print(tv1i.sum())
    
    print(tvis2i.sum())
    print(tu2i.sum())
    print(tv2i.sum())

2.3609519701766692j
-2.0000000000000004
3.6139131906290456
5.020889170727523j
-12.000000000000007
12.0


2.3609519701766692j
-2.0000000000000004
3.6139131906290456
5.020889170727523j
-12.000000000000004
12.0
-1.2269784131548596j
-2.0000000000000004
-0.9355439111700462
-2.6093119756832692j
-12.000000000000007
-12.000000000000004


-1.2269784131548596j
-2.0000000000000004
-0.9355439111700462
-2.6093119756832692j
-12.000000000000004
-12.000000000000004
0.07502069982979263j
1.9999999999999998
-7.738774404025948
0.15954131166464033j
12.0
-36.0


0.07502069982979263j
1.9999999999999998
-7.738774404025948
0.15954131166464033j
12.0
-36.0
-0.27722034862503475j
1.9999999999999998
6.572617402685415
-0.589531124766075j
12.0
36.0


-0.27722034862503475j
1.9999999999999998
6.572617402685415
-0.589531124766075j
12.0
36.0


In [590]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


In [591]:
np.outer(x, y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [593]:
np.outer(y, x)

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [506]:
tu1 = np.zeros(W)
tvis1 = np.zeros(W, dtype=complex)
tv1 = np.zeros(W)

su = np.zeros(1)
sv = np.zeros(1)
svis = np.zeros(1, dtype=complex)


tu2 = np.zeros(W2)
tvis2 = np.zeros(W2, dtype=complex)
tv2 = np.zeros(W2)



In [452]:
from gridding_python_improved.gridding import grid_1d_from_2d

In [453]:

for i in range(nvis):
    su[0] = u[i]
    sv[0] = v[i]
    svis[0] = vis[i]
    grid_1d_from_2d(su, svis, du, W, beta, sv, tu1, tvis1, tv1)

    grid_1d_from_2d(tv1, tvis1, dv, W, beta, tu1, tv2, tvis2, tu2) # output arrays


In [404]:
print(tvis1.sum())
print(tu1.sum())
print(tv1.sum())

    
print(tvis2.sum())
print(tu2.sum())
print(tv1.sum())


-0.5926550220261849j
-2.0000000000000004
8.475364152705392
-1.2603631391341508j
-12.000000000000007
8.475364152705392
